# spring.application.name=fittrack

spring:
  application:
    name: fittrack
  datasource:
    url: jdbc:postgresql://localhost:5432/fittrack_db
    username: fittrack
    password: fittrack
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  # change for production
  secret: JEQsCfXbjKDw18cU/oIkNeiMS00KvFiMnbBhBhrawH3RrxUnQcuCNxLDz+mCrOaMGNYU25pZwDgt55OBJ+DODQ==
  expiration-ms: 86400000
